spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/grove-dev
          jwk-set-uri: http://localhost:8180/realms/grove-dev/protocol/openid-connect/certs

logging:
  level:
    com.grove: DEBUG
    org.springframework.security: DEBUG
