apiVersion: v1
kind: ServiceAccount
metadata:
  name: grove-domain
  namespace: grove
  labels:
    app: grove-domain
  annotations:
    # IRSA: populated per environment overlay
    eks.amazonaws.com/role-arn: ""
